In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.9.1'

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:354: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = check_array(X, dtype=np.int)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:95: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [24]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5800 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5018 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4702 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4508 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4368 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.7961
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4167 - accuracy: 0.8045
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4085 - accuracy: 0.8141
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3990 - accuracy: 0.8220
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3911 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 0.8635
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3369 - accuracy: 0.8622
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 0.8625
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 0.8612
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3360 - accuracy: 0.8641
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8639
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8622
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3373 - accuracy: 0.8622
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8631
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3368 - accuracy: 

In [38]:
ann.predict(sc.transform([[1 , 0 , 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

1/1 [==============================] - 0s 44ms/step


array([[0.06513991]], dtype=float32)

In [39]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1578   17]
 [ 303  102]]


0.84